DROP TABLE IF EXISTS "registro_conversiones" CASCADE;
DROP TABLE IF EXISTS "campañas_plataformas" CASCADE;
DROP TABLE IF EXISTS "campañas" CASCADE;
DROP TABLE IF EXISTS "plataformas" CASCADE;




CREATE TABLE "campañas" (
	"id_campaña" SERIAL NOT NULL UNIQUE,
	"nombre_campaña" VARCHAR(100) NOT NULL,
	"presupuesto" NUMERIC(10,2) NOT NULL,
	"fecha_incio" DATE NOT NULL,
	PRIMARY KEY("id_campaña")
);




CREATE TABLE "plataformas" (
	"id" SERIAL NOT NULL UNIQUE,
	"nombre_plataforma" VARCHAR(50) NOT NULL,
	"url_plataforma" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE "registro_conversiones" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tipo" VARCHAR(255) NOT NULL,
	"valor" NUMERIC(10,2) NOT NULL,
	"fecha_conversion" TIMESTAMP NOT NULL,
	"id de campaña" SERIAL NOT NULL,
	"idplataforma" SERIAL NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE "campañas/plataformas" (
	"id_campaña" SERIAL NOT NULL UNIQUE,
	"id_plataforma" SERIAL NOT NULL
);



ALTER TABLE "registro_conversiones"
ADD FOREIGN KEY("id de campaña") REFERENCES "campañas"("id_campaña")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "registro_conversiones"
ADD FOREIGN KEY("idplataforma") REFERENCES "plataformas"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "campañas"
ADD FOREIGN KEY("id_campaña") REFERENCES "campañas/plataformas"("id_campaña")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "campañas/plataformas"
ADD FOREIGN KEY("id_plataforma") REFERENCES "plataformas"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;



INSERT INTO "campañas" ("nombre_campaña", "presupuesto", "fecha_inicio")
VALUES 
('Campaña Verano', 5000.00, '2025-01-10'),
('Campaña Invierno', 3000.00, '2025-06-01');

INSERT INTO "plataformas" ("nombre_plataforma", "url_plataforma")
VALUES
('Google Ads', 'https://ads.google.com'),
('Facebook Ads', 'https://facebook.com/ads'),
('Instagram Ads', 'https://instagram.com/ads');

INSERT INTO "campañas_plataformas" ("id_campaña", "id_plataforma")
VALUES
(1, 1),
(1, 2), 
(2, 2), 
(2, 3); 


INSERT INTO "registro_conversiones" ("tipo", "valor", "fecha_conversion", "id_campaña", "id_plataforma")
VALUES
('Compra', 1200.50, '2025-01-15 14:23:00', 1, 1),
('Registro', 0.00, '2025-01-16 10:05:00', 1, 2),
('Compra', 800.00, '2025-06-10 18:45:00', 2, 2),
('Click', 0.00, '2025-06-11 12:30:00', 2, 3);



SELECT * FROM "campañas";


SELECT * FROM "plataformas";